{{- include "chart.validate" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  sources:
    - repoURL: {{ .Values.deployment.oss.repository.URL }}
      targetRevision: {{ .Values.deployment.oss.repository.branch }}
      path: "{{ .Values.deployment.oss.repository.baseDir }}/{{ .Values.deployment.oss.repository.appsDir }}"
      helm:
        valueFiles:
          - "values-{{ .Values.environment }}.yaml"
        values: |
          {{ omit .Values "argo-cd" | toYaml | nindent 10 }}
    {{- if .Values.deployment.saas.enabled }}
    - repoURL: {{ .Values.deployment.saas.repository.URL }}
      targetRevision: {{ .Values.deployment.saas.repository.branch }}
      path: "{{ .Values.deployment.saas.repository.baseDir }}/{{ .Values.deployment.saas.repository.appsDir }}"
      helm:
        valueFiles:
          - "values-{{ .Values.environment }}.yaml"
        values: |
          {{ omit .Values "argo-cd" | toYaml | nindent 10 }}
    {{- end }}

  destination:
    name: in-cluster
    namespace: argocd

  syncPolicy:
    retry:
      # limit: -1
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 10m
    automated:
      prune: true
      selfHeal: true
