{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-primary
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Cassandra..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/cassandra-primary" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "cassandra-primary",
                  "toolType": "CASSANDRA",
                  "name": "Cassandra Database",
                  "description": "Cassandra Distributed Database",
                  "toolUrls": [
                    {
                      "url": "cassandra://cassandra.datasources.svc.cluster.local",
                      "port": "9042",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "NoSQL Database",
                  "platformCategory": "OpenFrame Datasource",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Datasource",
                  "layerOrder": 3,
                  "layerColor": "#616161",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/health",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/api/v1/*","/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Cassandra Registration complete."
{{- end }}
