environment: dev

global:
  registerJob:
    enabled: true

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

server:
  image: 
    repo: ghcr.io/flamingo-stack/openframe-oss-tenant/meshcentral
    tag: latest
