environment: dev

deployment:
  oss:
    enabled: true    
    # Ingress configuration - enable only ONE of the following
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx
      ngrok:
        enabled: false  # Enable ngrok ingress for external access
        credentials:
          apiKey: ""
          authtoken: ""
    repository:
      baseDir: manifests
      appsDir: apps
      URL: https://github.com/flamingo-stack/openframe-oss-tenant.git
      branch: main
      autoSync: true
  saas:
    enabled: false
    # Ingress configuration for SaaS deployment
    ingress:
      localhost:
        enabled: false   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: true 
        privateDomain: "internal.flamingo.cx"
        tenantID: "cluster-1001" 

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""
    
servicemonitor:
  enabled: true
registerJob:
  enabled: true

# Application configuration
image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-gateway
  tag: latest
