environment: dev

deployment:
  oss:
    enabled: true    
    config:
      repoName: openframe-oss-tenant-cfg
      branch: main
  saas:
    enabled: false
    config:
      repoName: openframe-saas-tenant-cfg
      branch: main
      password: ""  # GitHub Token for private config repo access

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
servicemonitor:
  enabled: true

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-config
  tag: latest
