{{- if ne .Values.registry.docker.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-pat-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.registry.docker.server .Values.registry.docker.username .Values.registry.docker.password .Values.registry.docker.email | b64enc | quote }}
{{- end }}
