{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-exporter
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Redis Exporter..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/redis-exporter" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "redis-exporter",
                  "toolType": "REDIS_EXPORTER",
                  "name": "Redis Exporter",
                  "description": "Redis Metrics Exporter for Prometheus",
                  "toolUrls": [
                    {
                      "url": "http://redis-exporter.datasources.svc.cluster.local",
                      "port": "9121",
                      "type": "API"
                    }
                  ],
                  "category": "Monitoring",
                  "platformCategory": "OpenFrame Service",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Monitoring",
                  "layerOrder": 5,
                  "layerColor": "#D84315",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/metrics",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Redis Exporter Registration complete."
{{- end }}
