deployment:
  saas:
    enabled: true
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false
        gkeSecurityGroup: "gke-security-groups@flamingo.cx"

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
