environment: qa

apps:
  openframe-config:
    values:
      image:
        tag: latest
  openframe-management:
    values:
      image:
        tag: latest
  openframe-external-api: 
    values:
      image:
        tag: latest
  openframe-api: 
    values:
      image:
        tag: latest
  openframe-authorization-server:
    values:
      image:
        tag: latest
  openframe-gateway: 
    values:
      image:
        tag: latest
  openframe-client: 
    values:
      image:
        tag: latest
  openframe-stream: 
    values:
      image:
        tag: latest
  openframe-frontend: 
    values:
      image:
        tag: latest

  # authentik: 
  #   values:
  #     postgres:
  #       image: 
  #         tag: latest
  fleetmdm: 
    values:
      server:
        image: 
          tag: latest
  meshcentral: 
    values:
      server:
        image: 
          tag: latest
  tactical-rmm: 
    values:
      tactical:
        frontend:
          image:
            tag: latest
        nginx:
          image:
            tag: latest
        base:
          image:
            tag: latest
