environment: stage

apps:
  openframe-config:
    values:
      image:
        tag: 0.0.20
  openframe-management:
    values:
      image:
        tag: 0.0.20
  openframe-external-api: 
    values:
      image:
        tag: 0.0.20
  openframe-api: 
    values:
      image:
        tag: 0.0.20
  openframe-authorization-server:
    values:
      image:
        tag: 0.0.20
  openframe-gateway: 
    values:
      image:
        tag: 0.0.20
  openframe-client: 
    values:
      image:
        tag: 0.0.20
  openframe-stream: 
    values:
      image:
        tag: 0.0.20
  openframe-frontend: 
    values:
      image:
        tag: 0.0.20

  # authentik: 
  #   values:
  #     postgres:
  #       image: 
  #         tag: 0.0.20
  fleetmdm: 
    values:
      server:
        image: 
          tag: 0.0.20
  meshcentral: 
    values:
      server:
        image: 
          tag: 0.0.20
  tactical-rmm: 
    values:
      tactical:
        frontend:
          image:
            tag: 0.0.20
        nginx:
          image:
            tag: 0.0.20
        base:
          image:
            tag: 0.0.20
