{{- range $name, $app := .Values.apps }}
  {{- $skip := include "app.skip" (list $name $app $.Values) | trim | lower }}
  {{- if ne $skip "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $app.syncWave | default "0" }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: {{ $app.project | default "default" }}

  sources:
    - repoURL: {{ $.Values.deployment.oss.repository.URL }}
      targetRevision: {{ $.Values.deployment.oss.repository.branch }}
      path: "{{ $.Values.deployment.oss.repository.baseDir }}/{{ $app.namespace }}/{{ $name }}"
      helm:
        values: |
          environment: {{ $.Values.environment }}
          deployment:
{{ toYaml $.Values.deployment | indent 12 }}
          registry:
{{ toYaml $.Values.registry | indent 12 }}
{{- $appValues := include "app.values" (list $name $app $.Values) | trim }}
{{- if ne $appValues "" }}
{{ $appValues | indent 10 }}
{{- end }}

  destination:
    name: in-cluster
    namespace: {{ $app.namespace }}

  {{- $autoSync := (hasKey $.Values.deployment.oss.repository "autoSync") | ternary $.Values.deployment.oss.repository.autoSync true }}
  syncPolicy:
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30m
    automated:
      prune: {{ $autoSync }}
      selfHeal: {{ $autoSync }}
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply={{ (get $app "syncOptions" | default dict).ServerSideApply | default false }}
      - RespectIgnoreDifferences={{ (get $app "syncOptions" | default dict).RespectIgnoreDifferences | default false }}

  {{- if get ($app.syncOptions | default dict) "RespectIgnoreDifferences" | default false }}
  ignoreDifferences:
{{ include (printf "app-helpers.%s.ignoreDifferences" $name) . | indent 4 }}
  {{- end }}
  
  {{- end }}
{{- end }}
