{{- if .Values.global.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-redis
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Authentik Redis..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/authentik-redis" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "authentik-redis",
                  "toolType": "REDIS",
                  "name": "Authentik Redis",
                  "description": "Redis Backend for Authentik",
                  "toolUrls": [
                    {
                      "url": "redis://authentik-redis-0.authentik-redis.integrated-tools.svc.cluster.local",
                      "port": "6379",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "In-Memory Database",
                  "platformCategory": "Integrated Tool",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Integrated Tools",
                  "layerOrder": 5,
                  "layerColor": "#B71C1C",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Authentik Redis Registration complete."
{{- end }}
