{{- if .Values.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ngrok-operator
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Ngrok Operator..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/ngro-operator" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "ngrok operator",
                  "toolType": "NGROK_OPERATOR",
                  "name": "Ngrok Operator",
                  "description": "Ngrok Operator Kubernetes Controller",
                  "toolUrls": [
                    {
                      "url": "http://ngrok-operator-manager.platform.svc.cluster.local",
                      "port": "10254",
                      "type": "API"
                    }
                  ],
                  "category": "Ingress Controller",
                  "platformCategory": "OpenFrame Service",
                  "enabled": true,
                  "credentials": {},
                  "layer": "Networking",
                  "layerOrder": 1,
                  "layerColor": "#1565C0",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/healthz",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics","/healthz"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Ngrok Operator Registration complete."
{{- end }}
