environment: dev

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
servicemonitor:
  enabled: true

image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-authorization-server
  tag: latest