{{- if .Values.global.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: fleetmdm-mysql
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: fleetmdm-mysql
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fleetmdm-mysql
              key: MYSQL_PASSWORD

        command:
          - /bin/sh
          - -c
          - |
            echo "Registering FleetMDM MySQL..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/fleetmdm-mysql" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "fleetmdm-mysql",
                  "toolType": "MYSQL",
                  "name": "FleetMDM MySQL",
                  "description": "MySQL Database Backend for FleetMDM",
                  "toolUrls": [
                    {
                      "url": "mysql://fleetmdm-mysql-0.fleetmdm-mysql.integrated-tools.svc.cluster.local",
                      "port": "3306",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "SQL Database",
                  "platformCategory": "Integrated Tool",
                  "enabled": true,
                  "credentials": {
                    "username": "'"${MYSQL_USER}"'",
                    "password": "'"${MYSQL_PASSWORD}"'"
                  },
                  "layer": "Integrated Tools",
                  "layerOrder": 6,
                  "layerColor": "#00796B",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "FleetMDM MySQL Registration complete."
{{- end }}         
 