{{- if .Values.global.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-postgres
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: authentik-postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: POSTGRES_PASSWORD
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Authentik PostgreSQL..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/authentik-postgres" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "authentik-postgres",
                  "toolType": "POSTGRESQL",
                  "name": "Authentik PostgreSQL",
                  "description": "PostgreSQL Database Backend for Authentik",
                  "toolUrls": [
                    {
                      "url": "postgresql://authentik-postgres-0.authentik-postgres.integrated-tools.svc.cluster.local",
                      "port": "5432",
                      "type": "DATABASE"
                    }
                  ],
                  "category": "SQL Database",
                  "platformCategory": "Integrated Tool",
                  "enabled": true,
                  "credentials": {
                    "username": "'"${POSTGRES_USER}"'",
                    "password": "'"${POSTGRES_PASSWORD}"'"
                  },
                  "layer": "Integrated Tools",
                  "layerOrder": 6,
                  "layerColor": "#3949AB",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Authentik PostgreSQL Registration complete."
{{- end }}
