{{- if .Values.global.registerJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: authentik-server
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      {{- if ne .Values.registry.docker.password "" }}
      imagePullSecrets:
        - name: docker-pat-secret
      {{- end }}
      
      containers:
      - name: register
        image: curlimages/curl:8.5.0
        env:
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              name: authentik-server
              key: AUTHENTIK_BOOTSTRAP_EMAIL
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-server
              key: AUTHENTIK_BOOTSTRAP_PASSWORD
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentik-server
              key: AUTHENTIK_BOOTSTRAP_TOKEN
        command:
          - /bin/sh
          - -c
          - |
            echo "Registering Authentik..."
            echo "Waiting for OpenFrame Management API to become reachable..."
            until curl --head --fail --silent http://openframe-management.microservices.svc.cluster.local:8096/management/v1/health; do
              echo "Still waiting..."
              sleep 10
            done
            curl --verbose --show-error --fail \
              -X POST "http://openframe-management.microservices.svc.cluster.local:8095/v1/tools/authentik-server" \
              -H "Content-Type: application/json" \
              -d '{
                "tool": {
                  "id": "authentik",
                  "toolType": "AUTHENTIK",
                  "name": "Authentik SSO",
                  "description": "Authentik Identity Provider",
                  "toolUrls": [
                    { "url": "http://authentik-server.integrated-tools.svc.cluster.local", "port": "9000", "type": "API" },
                    { "url": "http://authentik-server.integrated-tools.svc.cluster.local", "port": "9000", "type": "DASHBOARD" }
                  ],
                  "category": "Identity Provider",
                  "platformCategory": "Integrated Tool",
                  "enabled": true,
                  "credentials": {
                    "username": "'"${AUTHENTIK_BOOTSTRAP_EMAIL}"'",
                    "password": "'"${AUTHENTIK_BOOTSTRAP_PASSWORD}"'",
                    "apiKey": {
                      "key": "'"${AUTHENTIK_BOOTSTRAP_TOKEN}"'",
                      "type": "BEARER_TOKEN"
                    }
                  },
                  "layer": "Integrated Tools",
                  "layerOrder": 4,
                  "layerColor": "#455A64",
                  "metricsPath": "/metrics",
                  "healthCheckEndpoint": "/",
                  "healthCheckInterval": 30,
                  "connectionTimeout": 5000,
                  "readTimeout": 5000,
                  "allowedEndpoints": ["/api/v1/*","/metrics"],
                  "debeziumConnectors": []
                }
              }' \
              --retry-delay 2 \
              --retry-all-errors
            echo "Authentik Registration complete."
{{- end }}
