apiVersion: v2
name: cassandra-wrapper
description: Wrapper chart for Ð¡assandra
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cassandra
    version: ">=12.3.9"
    repository: oci://registry-1.docker.io/bitnamicharts  # should be migrated
