{{- if and .Values.deployment.saas.enabled .Values.deployment.saas.ingress.gcp.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telepresence-user
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods", "pods/portforward", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectaccessreviews"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telepresence-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telepresence-user
subjects:
- kind: Group
  name: "{{ .Values.deployment.saas.ingress.gcp.gkeSecurityGroup }}"
  apiGroup: rbac.authorization.k8s.io

{{- end }}