apiVersion: v2
name: kafka-wrapper
description: Wrapper chart for Kafka
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kafka
    version: ">=32.3.14"
    repository: oci://registry-1.docker.io/bitnamicharts  # should be migrated
