environment: dev

deployment:
  oss:
    enabled: true    
    # Ingress configuration - enable only ONE of the following
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx
      ngrok:
        enabled: false  # Enable ngrok ingress for external access
        credentials:
          apiKey: ""
          authtoken: ""
    repository:
      baseDir: manifests
      appsDir: apps
      URL: https://github.com/flamingo-stack/openframe-oss-tenant.git
      branch: main
      autoSync: true
    config:
      repoName: openframe-oss-tenant-cfg
      branch: main
  saas:
    enabled: false
    # Ingress configuration for SaaS deployment
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false 

        publicDomain: "internal.flamingo.cx"
        privateDomain: "internal.flamingo.cx"

        gkeSecurityGroup: "gke-security-groups@flamingo.cx"
        tenantID: "example" 

    repository:
      baseDir: manifests
      appsDir: apps
      URL: https://github.com/flamingo-stack/openframe-saas-tenant.git
      branch: main
      autoSync: true
      password: ""  # GitHub PAT for private repo access
    config:
      repoName: openframe-saas-tenant-cfg
      branch: main
      password: ""  # GitHub Token for private config repo access
  
registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""
  ghcr:
    server: ghcr.io
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
