{{- if ne .Values.registry.ghcr.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pat-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\"}}}" .Values.registry.ghcr.server .Values.registry.ghcr.username .Values.registry.ghcr.password .Values.registry.ghcr.email | b64enc | quote }}
{{- end }}
