environment: dev

global:
  registerJob:
    enabled: true

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

tactical:
  frontend:
    image:
      repo: ghcr.io/flamingo-stack/openframe-oss-tenant/tactical-frontend
      tag: latest
  nginx:
    image:
      repo: ghcr.io/flamingo-stack/openframe-oss-tenant/tactical-nginx
      tag: latest
  base:
    image:
      repo: ghcr.io/flamingo-stack/openframe-oss-tenant/tactical-base
      tag: latest
