environment: dev

deployment:
  oss:
    enabled: true
    ingress:
      custom:
        enabled: true
        host: openframe.techm.world
        tlsSecretName: openframe-techm-world-tls
      localhost:
        enabled: false
      ngrok:
        enabled: false  # Enable ngrok ingress for external access
        credentials:
          apiKey: ""
          authtoken: ""
    repository:
      baseDir: manifests
      appsDir: apps
      URL: https://github.com/flamingo-stack/openframe-oss-tenant.git
      branch: main
      autoSync: true
  saas:
    enabled: false
    # Ingress configuration for SaaS deployment
    ingress:
      localhost:
        enabled: true   # Enable localhost ingress with nginx for SaaS
      gcp:
        enabled: false 
        publicDomain: "flamingo.cx"

registry:
  docker:
    server: https://index.docker.io/v1/
    username: ""
    password: ""
    email: ""

registerJob:
  enabled: true
 
image:
  repo: ghcr.io/flamingo-stack/openframe-oss-tenant/openframe-frontend
  tag: latest
