apiVersion: v2
name: redis-wrapper
description: Wrapper chart for Redis
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: redis
    version: ">=21.2.10"
    repository: oci://registry-1.docker.io/bitnamicharts  # should be migrated
