registerJob:
  enabled: true

redis:
  # bitnamilegacy
  image:
    repository: bitnamilegacy/redis
    tag: 8.2.1-debian-12-r0
  
  global:
    # bitnamilegacy
    security:
      allowInsecureImages: true

  auth:
    enabled: false
    password: ""
    # existingSecret: ""
  #   password: "admin"
  #   existingSecret: "redis-secret"
  #   existingSecretPasswordKey: "redis-password"
  replica:
    replicaCount: 1

  metrics:
    # bitnamilegacy
    image:
      repository: bitnamilegacy/redis-exporter
      tag: 1.76.0-debian-12-r0

    enabled: true
    serviceMonitor:
      enabled: true
    # podMonitor:
    #   enabled: true
