name: Openframe Test

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================

permissions:
  contents: write
  packages: write
  actions: write
  pull-requests: write
  attestations: write
  id-token: write
  pages: write

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - 'openframe/**'
      - 'integrated-tools/**'
      - 'pom.xml'
      - '.github/**'
      - 'manifests/**'
      - 'clients/**'

concurrency:
  group: pr-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

env:
  REGISTRY: "ghcr.io"
  ORGANISATION: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  HELM_VALUES_FILE: "cli/helm-values.yaml"


# =============================================================================
# JOBS
# =============================================================================

jobs:
  changes:
    name: Changes
    uses: ./.github/workflows/changes.yml
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.draft

  matrix:
    name: Matrix
    uses: ./.github/workflows/matrix.yml
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.draft


  build_images:
    name: "Build: ${{ matrix.name }}"
    needs: [changes, matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.images_matrix) }}
    steps:
      - name: Check if build should run
        id: should_run
        run: echo "run=${{ github.event_name == 'pull_request' && !github.event.pull_request.draft && fromJSON(toJSON(needs.changes.outputs))[matrix.name] == 'true' }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.should_run.outputs.run == 'true'
        with:
          fetch-depth: 1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        if: steps.should_run.outputs.run == 'true'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.should_run.outputs.run == 'true'
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.should_run.outputs.run == 'true'

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        if: steps.should_run.outputs.run == 'true'
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANISATION }}/${{ env.REPOSITORY }}/${{ matrix.name }}
          tags: |
            type=ref,event=tag
            type=raw,value=${{ needs.changes.outputs.test_commit_sha }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.version }},enable=${{ inputs.version != '' }}
          labels: |
            org.opencontainers.image.vendor=${{ env.ORGANISATION }}
            org.opencontainers.image.description=OpenFrame is a platform for building and deploying AI agents.
            org.opencontainers.image.licenses=Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
 
      - name: Format build arguments
        id: format_args
        uses: ./.github/steps/docker-format-build-args
        if: steps.should_run.outputs.run == 'true'
        with:
          build_args: ${{ toJSON(matrix.build_args) }}
        env:
          BUILD_ARGS: ${{ steps.format_args.outputs.formatted_args }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v6
        if: steps.should_run.outputs.run == 'true'
        with:
          # need to copy the pom.xml from the root so it builds with the lib version correctly
          context: ${{ matrix.context || matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          build-args: |
            GITHUB_ACTOR=${{ github.actor }}
            ${{ env.BUILD_ARGS }}


  test:
    name: Run Tests
    needs: [build_images, changes, matrix]
    timeout-minutes: 60
    runs-on: Linux-x64
    env:
      CARGO_INCREMENTAL: 0
    if: |
      github.event_name == 'pull_request' &&
      !github.event.pull_request.draft &&
      !startsWith(github.head_ref, 'release/') &&
      !startsWith(github.head_ref, 'revert/') &&
      !startsWith(github.head_ref, 'hotfix/')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install tools and validate environment
        uses: ./.github/steps/requirements-for-run.sh

      - name: Override helm values
        uses: ./.github/steps/helm-override
        with:
          matrix: ${{ needs.matrix.outputs.images_matrix }}
          changes: ${{ toJSON(needs.changes.outputs) }}
          commit-sha: ${{ needs.changes.outputs.test_commit_sha }}
          helm-values-file: ${{ env.HELM_VALUES_FILE }}
          branch-name: ${{ github.head_ref }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-email: "dmtkov@flamingo.cx"

      - name: Run tests scripts
        working-directory: cli
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENFRAME_CLI_URL: "https://github.com/${{ env.ORGANISATION }}/openframe-oss-tenant/releases/latest/download/openframe-cli_linux_amd64.tar.gz"
        run: |
          curl -fL "$OPENFRAME_CLI_URL" | tar -xz -C /tmp && install -m 0755 /tmp/openframe /usr/local/bin/openframe
          openframe bootstrap --deployment-mode=oss-tenant --non-interactive --verbose

      - name: Setup Telepresence
        uses: ./.github/steps/setup-telepresence

      - name: Run Tests
        id: tests
        env:
          API_BASE_URL: http://localhost:8100
        run: |
          cd openframe-e2e-tests
          mvn test -Dgroups="smoke"
        continue-on-error: true

      - name: Generate and Deploy Allure Report
        if: always()
        uses: ./.github/steps/allure-report
        with:
          pr-number: ${{ github.event.pull_request.number }}
          test-status: ${{ steps.tests.outcome }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


  test_clients:
    name: "Test Rust Client: ${{ matrix.name }} on ${{ matrix.os }}"
    needs: [changes, matrix]
    runs-on: "${{ matrix.os }}-latest"
    env:
      CARGO_INCREMENTAL: 0
      BINARY_NAME: ${{ matrix.name }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.clients_matrix) }}

    steps:
      - name: Check if build should run
        id: should_run
        run: echo "run=${{ github.event_name == 'pull_request' && !github.event.pull_request.draft && fromJSON(toJSON(needs.changes.outputs))[matrix.id || matrix.name] == 'true' }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.should_run.outputs.run == 'true'
        with:
          fetch-depth: 1

      - name: Prepare Rust tools
        uses: ./.github/steps/rust-setup
        if: steps.should_run.outputs.run == 'true'
        with:
          path: ${{ matrix.path }}
          toolchain: stable
          targets: ${{ matrix.target }}
          components: clippy, rustfmt
          shared-key: ${{ runner.os }}-${{ runner.arch }}

      - name: Run lint
        working-directory: ${{ matrix.path }}
        if: steps.should_run.outputs.run == 'true'
        run: |
          make lint
        continue-on-error: true

      - name: Test client
        working-directory: ${{ matrix.path }}
        if: steps.should_run.outputs.run == 'true'
        run: |
          if [[ "${{ matrix.os }}" == "macos" ]]; then
            IFS=',' read -ra ARCHITECTURES <<< "${{ matrix.target }}"
            for RUST_TARGET in "${ARCHITECTURES[@]}"; do
              RUST_TARGET=$(echo "$RUST_TARGET" | tr -d '[:space:]')
              make build TARGET="$RUST_TARGET"
            done
          else
            make build TARGET="${{ matrix.target }}"
          fi

      - name: Upload Rust Artifacts for Windows / Linux
        if: steps.should_run.outputs.run == 'true' && runner.os != 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.name }}-${{ matrix.os }}"
          path: "${{ matrix.target_path }}/${{ matrix.target }}/release/${{ env.BINARY_NAME }}${{ matrix.os == 'windows' && '.exe' || '' }}"
          if-no-files-found: warn
          retention-days: 1
          compression-level: 9


  test_helm:
    name: "Test Helm Chart"
    needs: [matrix, changes]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.draft && 
      contains(needs.changes.outputs.helm, 'true')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
      
      - name: Install Helm unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      
      - name: Test Chart
        run: |
          helm template app ./manifests/app-of-apps 
          helm unittest ./manifests/app-of-apps 


  cleanup:
    name: "Cleanup ${{ matrix.name }}"
    needs: [changes, matrix, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft && always()
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.images_matrix) }}
    steps:
      - uses: actions/checkout@v4
        if: contains(needs.changes.outputs[matrix.name], 'true')

      - name: Login to GitHub Registry
        if: contains(needs.changes.outputs[matrix.name], 'true')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Delete the CI tag
        if: contains(needs.changes.outputs[matrix.name], 'true')
        uses: dataaxiom/ghcr-cleanup-action@v1
        continue-on-error: true
        with:
          package: ${{ env.REPOSITORY }}/${{ matrix.name }}
          delete-ghost-images: true
          delete-tags: ${{ needs.changes.outputs.test_commit_sha }}


  final-checks:
    name: Final tests
    needs: [test]
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && 
      !github.event.pull_request.draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Verify values are clean
        run: |
          [ -f "$HELM_VALUES_FILE" ] || { echo "Error: $HELM_VALUES_FILE not found"; exit 1; }
          [ ! -s "$HELM_VALUES_FILE" ] || { echo "Error: $HELM_VALUES_FILE is not empty"; cat "$HELM_VALUES_FILE"; exit 1; }
          echo "$HELM_VALUES_FILE is empty"
